name: A2L Fuzzing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run A2L Fuzzing
      run: cd a2l
      run: go test -fuzz=./a2l/FuzzParseA2L -fuzztime=30s -v
