name: SREC19 Fuzzing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run A2L Fuzzing
      run: cd srec19
      run: go test -fuzz=./srec19/FuzzParseHex -fuzztime=30s -v
